export const REQUEST = 'REQUEST'
export const SUCCESS = 'SUCCESS'
export const FAILURE = 'FAILURE'
export const LOADING = 'LOADING'
export const REQUEST_PAGE = 'REQUEST_PAGE'
export const IS_SCROLLING = 'IS_SCROLLING'
export const ADD_FAVOURITE = 'ADD_FAVOURITE'
